import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdir, readFile, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';

if(process.platform!=='win32')throw new Error('原生测试需要 Windows WebView2');
const port=9236;
const server=net.createServer();
await new Promise((resolve,reject)=>server.once('error',reject).listen(port,'127.0.0.1',resolve));
await new Promise(resolve=>server.close(resolve));
const report={runtime:'Tauri / WebView2',date:new Date().toISOString(),checks:[],hardwareTested:false};
await mkdir('test-results/native-smoke',{recursive:true});
const app=spawn(path.resolve('src-tauri/target/release/zhiliao-studio.exe'),[],{windowsHide:true,stdio:'ignore',env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:`--remote-debugging-port=${port}`,WEBVIEW2_USER_DATA_FOLDER:path.resolve('test-results/native-profile')}});
app.on('error',e=>{console.error(e);process.exitCode=1;});
let browser;
let exportedLog;
try{
  for(let attempt=0;attempt<90;attempt++){
    if(app.exitCode!==null)throw new Error(`原生程序提前退出：${app.exitCode}`);
    try{const response=await fetch(`http://127.0.0.1:${port}/json/version`);if(response.ok)break;}catch{}
    await new Promise(resolve=>setTimeout(resolve,500));
  }
  browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
  const context=browser.contexts()[0];
  let page=context.pages()[0];
  if(!page)page=await context.waitForEvent('page');
  await expect(page.getByRole('heading',{name:/知了1号/})).toBeVisible();
  if(!/tauri\.localhost|tauri:\/\//.test(page.url()))throw new Error('不是打包后的应用页面');
  report.checks.push('发布程序离线资源载入');
  const nativePorts=await page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('ports'));
  report.ports=nativePorts;
  if(nativePorts.some(port=>!port.name||!port.description))throw new Error('串口信息缺少名称或描述');
  report.checks.push(`真实串口枚举成功：${nativePorts.length} 个端口`);
  await page.getByRole('combobox',{name:'通道',exact:true}).selectOption('serial');
  await page.getByRole('combobox',{name:'端口',exact:true}).click();
  if(nativePorts.some(port=>port.name==='COM9')){
    await expect(page.getByRole('option',{name:/\(COM9\)/})).toBeVisible();
    await page.getByRole('option',{name:/\(COM9\)/}).click();
    await page.getByRole('combobox',{name:'端口',exact:true}).click();
  }
  await page.screenshot({path:'test-results/native-smoke/native-ports.png',animations:'disabled'});
  await page.keyboard.press('Escape');
  report.checks.push('Windows友好名称与自定义串口列表');
  const invalidFrame=await page.evaluate(async()=>{try{await window.__TAURI_INTERNALS__.invoke('send',{bytes:[0xfd,0,1,0x99]});return false;}catch{return true;}});
  if(!invalidFrame)throw new Error('后端未拒绝无效命令');
  report.checks.push('原生后端拒绝非法命令');
  const captureGuard=await page.evaluate(async()=>{try{await window.__TAURI_INTERNALS__.invoke('capture_version');return false;}catch(error){return String(error).includes('串口未连接');}});
  if(!captureGuard)throw new Error('版本采集IPC未正确注册或缺少连接校验');
  report.checks.push('原生版本采集IPC注册与连接校验');
  await page.getByRole('combobox',{name:'通道',exact:true}).selectOption('sim');
  await page.getByRole('button',{name:'连接设备',exact:true}).click();
  await expect(page.getByText('已从模块读取')).toBeVisible();
  await page.getByRole('button',{name:'开始播报'}).click();
  await expect(page.getByText(/1 \/ 1 段已完成/)).toBeVisible();
  report.checks.push('原生窗口中的模拟连接、配置同步与播放完成');
  const downloads = await page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('log_export_directory'));
  let browserDownloads = 0;
  page.on('download',()=>browserDownloads++);
  await page.getByRole('button',{name:'导出日志',exact:true}).click();
  const exportDialog = page.getByRole('dialog',{name:'导出日志'});
  await expect(exportDialog).toBeVisible();
  await expect(exportDialog).toContainText(downloads);
  const logName = `cicada-native-${Date.now()}`;
  await exportDialog.getByLabel('文件名',{exact:true}).fill(logName);
  await page.screenshot({path:'test-results/native-smoke/native-download.png'});
  await exportDialog.getByRole('button',{name:'下载文件',exact:true}).click();
  await expect(exportDialog.getByRole('status')).toContainText('文件已保存');
  exportedLog = (await exportDialog.getByRole('status').locator('p').textContent()).trim();
  if(path.dirname(exportedLog)!==downloads || path.basename(exportedLog)!==`${logName}.log`)throw new Error('导出路径不符合系统下载目录与指定文件名');
  expect(await readFile(exportedLog,'utf8')).toContain('FD 00 01 21');
  expect(browserDownloads).toBe(0);
  await page.screenshot({path:'test-results/native-smoke/native-download-saved.png'});
  await exportDialog.getByRole('button',{name:'完成',exact:true}).click();
  report.checks.push('主题弹窗直接保存 UTF-8 日志到下载目录，无浏览器下载事件，显示实际路径');
  await page.screenshot({path:'test-results/native-smoke/native-release.png'});
  await page.getByRole('button',{name:'最大化或还原'}).click();
  await expect.poll(()=>page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('plugin:window|is_maximized',{label:'main'}))).toBe(true);
  await page.getByRole('button',{name:'最大化或还原'}).click();
  await expect.poll(()=>page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('plugin:window|is_maximized',{label:'main'}))).toBe(false);
  report.checks.push('原生最大化与还原');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'设置',exact:true})).toBeVisible();
  const about=page.getByRole('region',{name:'关于',exact:true});
  await expect(about).toContainText('Mzee');
  await expect(about).toContainText('上海玖驱科技有限公司');
  await expect(about.getByRole('link',{name:'xiemaths@outlook.com'})).toHaveAttribute('href','mailto:xiemaths@outlook.com');
  report.checks.push('作者、公司和联系邮箱完整展示');
  await page.screenshot({path:'test-results/native-smoke/native-settings.png',animations:'disabled'});
  report.checks.push('状态栏设置打开模态子窗口');
  await page.getByRole('combobox',{name:'界面语言',exact:true}).selectOption('en');
  await expect(page.getByRole('dialog',{name:'Settings',exact:true})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('plugin:window|title',{label:'main'}))).toBe('Cicada One · CICADA-1');
  await page.screenshot({path:'test-results/native-smoke/native-settings-en.png',animations:'disabled'});
  await page.getByRole('combobox',{name:'Interface language',exact:true}).selectOption('zh');
  report.checks.push('中英文设置、原生窗口标题同步，串口会话保持');
  await page.getByRole('button',{name:'读取版本并断开',exact:true}).click();
  await expect(page.getByLabel('最近版本原始响应')).toContainText('58 53 49 4D');
  await page.getByRole('button',{name:'完成',exact:true}).click();
  await expect(page.getByRole('button',{name:'设置',exact:true})).toBeFocused();
  await expect(page.getByRole('button',{name:'连接设备',exact:true})).toBeEnabled();
  report.checks.push('原生窗口版本原始响应展示与查询后断开（模拟）');
  await page.getByRole('combobox',{name:'通道',exact:true}).selectOption('serial');
  await page.getByRole('combobox',{name:'端口',exact:true}).click();
  await page.getByPlaceholder('选择或输入 COM 口').fill('COM99999');
  await page.getByRole('button',{name:'使用端口',exact:true}).click();
  await page.getByRole('button',{name:'连接设备',exact:true}).click();
  await expect(page.getByRole('alert')).toBeVisible();
  report.checks.push('真实串口打开失败的可见错误反馈');
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await expect.poll(()=>app.exitCode,{timeout:7000}).not.toBeNull();
  report.checks.push('原生关闭按钮退出进程');
  await writeFile('test-results/native-smoke/native-report.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
}finally{
  if(exportedLog)await unlink(exportedLog).catch(()=>{});
  if(browser)await browser.close().catch(()=>{});
  if(app.exitCode===null)app.kill();
}
